
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Chef` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Chef
 * 
 */
export type ChefModel = runtime.Types.Result.DefaultSelection<Prisma.$ChefPayload>

export type AggregateChef = {
  _count: ChefCountAggregateOutputType | null
  _avg: ChefAvgAggregateOutputType | null
  _sum: ChefSumAggregateOutputType | null
  _min: ChefMinAggregateOutputType | null
  _max: ChefMaxAggregateOutputType | null
}

export type ChefAvgAggregateOutputType = {
  sortOrder: number | null
}

export type ChefSumAggregateOutputType = {
  sortOrder: number | null
}

export type ChefMinAggregateOutputType = {
  id: string | null
  name: string | null
  cuisine: string | null
  image: string | null
  sortOrder: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChefMaxAggregateOutputType = {
  id: string | null
  name: string | null
  cuisine: string | null
  image: string | null
  sortOrder: number | null
  active: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ChefCountAggregateOutputType = {
  id: number
  name: number
  cuisine: number
  image: number
  sortOrder: number
  active: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ChefAvgAggregateInputType = {
  sortOrder?: true
}

export type ChefSumAggregateInputType = {
  sortOrder?: true
}

export type ChefMinAggregateInputType = {
  id?: true
  name?: true
  cuisine?: true
  image?: true
  sortOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ChefMaxAggregateInputType = {
  id?: true
  name?: true
  cuisine?: true
  image?: true
  sortOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
}

export type ChefCountAggregateInputType = {
  id?: true
  name?: true
  cuisine?: true
  image?: true
  sortOrder?: true
  active?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ChefAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Chef to aggregate.
   */
  where?: Prisma.ChefWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chefs to fetch.
   */
  orderBy?: Prisma.ChefOrderByWithRelationInput | Prisma.ChefOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ChefWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chefs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chefs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Chefs
  **/
  _count?: true | ChefCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ChefAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ChefSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ChefMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ChefMaxAggregateInputType
}

export type GetChefAggregateType<T extends ChefAggregateArgs> = {
      [P in keyof T & keyof AggregateChef]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateChef[P]>
    : Prisma.GetScalarType<T[P], AggregateChef[P]>
}




export type ChefGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChefWhereInput
  orderBy?: Prisma.ChefOrderByWithAggregationInput | Prisma.ChefOrderByWithAggregationInput[]
  by: Prisma.ChefScalarFieldEnum[] | Prisma.ChefScalarFieldEnum
  having?: Prisma.ChefScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ChefCountAggregateInputType | true
  _avg?: ChefAvgAggregateInputType
  _sum?: ChefSumAggregateInputType
  _min?: ChefMinAggregateInputType
  _max?: ChefMaxAggregateInputType
}

export type ChefGroupByOutputType = {
  id: string
  name: string
  cuisine: string
  image: string | null
  sortOrder: number
  active: boolean
  createdAt: Date
  updatedAt: Date
  _count: ChefCountAggregateOutputType | null
  _avg: ChefAvgAggregateOutputType | null
  _sum: ChefSumAggregateOutputType | null
  _min: ChefMinAggregateOutputType | null
  _max: ChefMaxAggregateOutputType | null
}

export type GetChefGroupByPayload<T extends ChefGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ChefGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ChefGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ChefGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ChefGroupByOutputType[P]>
      }
    >
  >



export type ChefWhereInput = {
  AND?: Prisma.ChefWhereInput | Prisma.ChefWhereInput[]
  OR?: Prisma.ChefWhereInput[]
  NOT?: Prisma.ChefWhereInput | Prisma.ChefWhereInput[]
  id?: Prisma.StringFilter<"Chef"> | string
  name?: Prisma.StringFilter<"Chef"> | string
  cuisine?: Prisma.StringFilter<"Chef"> | string
  image?: Prisma.StringNullableFilter<"Chef"> | string | null
  sortOrder?: Prisma.IntFilter<"Chef"> | number
  active?: Prisma.BoolFilter<"Chef"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Chef"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Chef"> | Date | string
}

export type ChefOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cuisine?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChefWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.ChefWhereInput | Prisma.ChefWhereInput[]
  OR?: Prisma.ChefWhereInput[]
  NOT?: Prisma.ChefWhereInput | Prisma.ChefWhereInput[]
  name?: Prisma.StringFilter<"Chef"> | string
  cuisine?: Prisma.StringFilter<"Chef"> | string
  image?: Prisma.StringNullableFilter<"Chef"> | string | null
  sortOrder?: Prisma.IntFilter<"Chef"> | number
  active?: Prisma.BoolFilter<"Chef"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Chef"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Chef"> | Date | string
}, "id">

export type ChefOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cuisine?: Prisma.SortOrder
  image?: Prisma.SortOrderInput | Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ChefCountOrderByAggregateInput
  _avg?: Prisma.ChefAvgOrderByAggregateInput
  _max?: Prisma.ChefMaxOrderByAggregateInput
  _min?: Prisma.ChefMinOrderByAggregateInput
  _sum?: Prisma.ChefSumOrderByAggregateInput
}

export type ChefScalarWhereWithAggregatesInput = {
  AND?: Prisma.ChefScalarWhereWithAggregatesInput | Prisma.ChefScalarWhereWithAggregatesInput[]
  OR?: Prisma.ChefScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ChefScalarWhereWithAggregatesInput | Prisma.ChefScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Chef"> | string
  name?: Prisma.StringWithAggregatesFilter<"Chef"> | string
  cuisine?: Prisma.StringWithAggregatesFilter<"Chef"> | string
  image?: Prisma.StringNullableWithAggregatesFilter<"Chef"> | string | null
  sortOrder?: Prisma.IntWithAggregatesFilter<"Chef"> | number
  active?: Prisma.BoolWithAggregatesFilter<"Chef"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Chef"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Chef"> | Date | string
}

export type ChefCreateInput = {
  id?: string
  name: string
  cuisine: string
  image?: string | null
  sortOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChefUncheckedCreateInput = {
  id?: string
  name: string
  cuisine: string
  image?: string | null
  sortOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChefUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cuisine?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChefUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cuisine?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChefCreateManyInput = {
  id?: string
  name: string
  cuisine: string
  image?: string | null
  sortOrder?: number
  active?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ChefUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cuisine?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChefUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  cuisine?: Prisma.StringFieldUpdateOperationsInput | string
  image?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  sortOrder?: Prisma.IntFieldUpdateOperationsInput | number
  active?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ChefCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cuisine?: Prisma.SortOrder
  image?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChefAvgOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}

export type ChefMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cuisine?: Prisma.SortOrder
  image?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChefMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  cuisine?: Prisma.SortOrder
  image?: Prisma.SortOrder
  sortOrder?: Prisma.SortOrder
  active?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ChefSumOrderByAggregateInput = {
  sortOrder?: Prisma.SortOrder
}



export type ChefSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  cuisine?: boolean
  image?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["chef"]>

export type ChefSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  cuisine?: boolean
  image?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["chef"]>

export type ChefSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  cuisine?: boolean
  image?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["chef"]>

export type ChefSelectScalar = {
  id?: boolean
  name?: boolean
  cuisine?: boolean
  image?: boolean
  sortOrder?: boolean
  active?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ChefOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "cuisine" | "image" | "sortOrder" | "active" | "createdAt" | "updatedAt", ExtArgs["result"]["chef"]>

export type $ChefPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Chef"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    cuisine: string
    image: string | null
    sortOrder: number
    active: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["chef"]>
  composites: {}
}

export type ChefGetPayload<S extends boolean | null | undefined | ChefDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChefPayload, S>

export type ChefCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ChefFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ChefCountAggregateInputType | true
  }

export interface ChefDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Chef'], meta: { name: 'Chef' } }
  /**
   * Find zero or one Chef that matches the filter.
   * @param {ChefFindUniqueArgs} args - Arguments to find a Chef
   * @example
   * // Get one Chef
   * const chef = await prisma.chef.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ChefFindUniqueArgs>(args: Prisma.SelectSubset<T, ChefFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Chef that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ChefFindUniqueOrThrowArgs} args - Arguments to find a Chef
   * @example
   * // Get one Chef
   * const chef = await prisma.chef.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ChefFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ChefFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Chef that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefFindFirstArgs} args - Arguments to find a Chef
   * @example
   * // Get one Chef
   * const chef = await prisma.chef.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ChefFindFirstArgs>(args?: Prisma.SelectSubset<T, ChefFindFirstArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Chef that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefFindFirstOrThrowArgs} args - Arguments to find a Chef
   * @example
   * // Get one Chef
   * const chef = await prisma.chef.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ChefFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ChefFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Chefs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Chefs
   * const chefs = await prisma.chef.findMany()
   * 
   * // Get first 10 Chefs
   * const chefs = await prisma.chef.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const chefWithIdOnly = await prisma.chef.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ChefFindManyArgs>(args?: Prisma.SelectSubset<T, ChefFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Chef.
   * @param {ChefCreateArgs} args - Arguments to create a Chef.
   * @example
   * // Create one Chef
   * const Chef = await prisma.chef.create({
   *   data: {
   *     // ... data to create a Chef
   *   }
   * })
   * 
   */
  create<T extends ChefCreateArgs>(args: Prisma.SelectSubset<T, ChefCreateArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Chefs.
   * @param {ChefCreateManyArgs} args - Arguments to create many Chefs.
   * @example
   * // Create many Chefs
   * const chef = await prisma.chef.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ChefCreateManyArgs>(args?: Prisma.SelectSubset<T, ChefCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Chefs and returns the data saved in the database.
   * @param {ChefCreateManyAndReturnArgs} args - Arguments to create many Chefs.
   * @example
   * // Create many Chefs
   * const chef = await prisma.chef.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Chefs and only return the `id`
   * const chefWithIdOnly = await prisma.chef.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ChefCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ChefCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Chef.
   * @param {ChefDeleteArgs} args - Arguments to delete one Chef.
   * @example
   * // Delete one Chef
   * const Chef = await prisma.chef.delete({
   *   where: {
   *     // ... filter to delete one Chef
   *   }
   * })
   * 
   */
  delete<T extends ChefDeleteArgs>(args: Prisma.SelectSubset<T, ChefDeleteArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Chef.
   * @param {ChefUpdateArgs} args - Arguments to update one Chef.
   * @example
   * // Update one Chef
   * const chef = await prisma.chef.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ChefUpdateArgs>(args: Prisma.SelectSubset<T, ChefUpdateArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Chefs.
   * @param {ChefDeleteManyArgs} args - Arguments to filter Chefs to delete.
   * @example
   * // Delete a few Chefs
   * const { count } = await prisma.chef.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ChefDeleteManyArgs>(args?: Prisma.SelectSubset<T, ChefDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Chefs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Chefs
   * const chef = await prisma.chef.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ChefUpdateManyArgs>(args: Prisma.SelectSubset<T, ChefUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Chefs and returns the data updated in the database.
   * @param {ChefUpdateManyAndReturnArgs} args - Arguments to update many Chefs.
   * @example
   * // Update many Chefs
   * const chef = await prisma.chef.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Chefs and only return the `id`
   * const chefWithIdOnly = await prisma.chef.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ChefUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ChefUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Chef.
   * @param {ChefUpsertArgs} args - Arguments to update or create a Chef.
   * @example
   * // Update or create a Chef
   * const chef = await prisma.chef.upsert({
   *   create: {
   *     // ... data to create a Chef
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Chef we want to update
   *   }
   * })
   */
  upsert<T extends ChefUpsertArgs>(args: Prisma.SelectSubset<T, ChefUpsertArgs<ExtArgs>>): Prisma.Prisma__ChefClient<runtime.Types.Result.GetResult<Prisma.$ChefPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Chefs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefCountArgs} args - Arguments to filter Chefs to count.
   * @example
   * // Count the number of Chefs
   * const count = await prisma.chef.count({
   *   where: {
   *     // ... the filter for the Chefs we want to count
   *   }
   * })
  **/
  count<T extends ChefCountArgs>(
    args?: Prisma.Subset<T, ChefCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ChefCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Chef.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ChefAggregateArgs>(args: Prisma.Subset<T, ChefAggregateArgs>): Prisma.PrismaPromise<GetChefAggregateType<T>>

  /**
   * Group by Chef.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ChefGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ChefGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ChefGroupByArgs['orderBy'] }
      : { orderBy?: ChefGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ChefGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetChefGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Chef model
 */
readonly fields: ChefFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Chef.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ChefClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Chef model
 */
export interface ChefFieldRefs {
  readonly id: Prisma.FieldRef<"Chef", 'String'>
  readonly name: Prisma.FieldRef<"Chef", 'String'>
  readonly cuisine: Prisma.FieldRef<"Chef", 'String'>
  readonly image: Prisma.FieldRef<"Chef", 'String'>
  readonly sortOrder: Prisma.FieldRef<"Chef", 'Int'>
  readonly active: Prisma.FieldRef<"Chef", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Chef", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Chef", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Chef findUnique
 */
export type ChefFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * Filter, which Chef to fetch.
   */
  where: Prisma.ChefWhereUniqueInput
}

/**
 * Chef findUniqueOrThrow
 */
export type ChefFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * Filter, which Chef to fetch.
   */
  where: Prisma.ChefWhereUniqueInput
}

/**
 * Chef findFirst
 */
export type ChefFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * Filter, which Chef to fetch.
   */
  where?: Prisma.ChefWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chefs to fetch.
   */
  orderBy?: Prisma.ChefOrderByWithRelationInput | Prisma.ChefOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Chefs.
   */
  cursor?: Prisma.ChefWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chefs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chefs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Chefs.
   */
  distinct?: Prisma.ChefScalarFieldEnum | Prisma.ChefScalarFieldEnum[]
}

/**
 * Chef findFirstOrThrow
 */
export type ChefFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * Filter, which Chef to fetch.
   */
  where?: Prisma.ChefWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chefs to fetch.
   */
  orderBy?: Prisma.ChefOrderByWithRelationInput | Prisma.ChefOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Chefs.
   */
  cursor?: Prisma.ChefWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chefs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chefs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Chefs.
   */
  distinct?: Prisma.ChefScalarFieldEnum | Prisma.ChefScalarFieldEnum[]
}

/**
 * Chef findMany
 */
export type ChefFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * Filter, which Chefs to fetch.
   */
  where?: Prisma.ChefWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Chefs to fetch.
   */
  orderBy?: Prisma.ChefOrderByWithRelationInput | Prisma.ChefOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Chefs.
   */
  cursor?: Prisma.ChefWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Chefs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Chefs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Chefs.
   */
  distinct?: Prisma.ChefScalarFieldEnum | Prisma.ChefScalarFieldEnum[]
}

/**
 * Chef create
 */
export type ChefCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * The data needed to create a Chef.
   */
  data: Prisma.XOR<Prisma.ChefCreateInput, Prisma.ChefUncheckedCreateInput>
}

/**
 * Chef createMany
 */
export type ChefCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Chefs.
   */
  data: Prisma.ChefCreateManyInput | Prisma.ChefCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Chef createManyAndReturn
 */
export type ChefCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * The data used to create many Chefs.
   */
  data: Prisma.ChefCreateManyInput | Prisma.ChefCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Chef update
 */
export type ChefUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * The data needed to update a Chef.
   */
  data: Prisma.XOR<Prisma.ChefUpdateInput, Prisma.ChefUncheckedUpdateInput>
  /**
   * Choose, which Chef to update.
   */
  where: Prisma.ChefWhereUniqueInput
}

/**
 * Chef updateMany
 */
export type ChefUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Chefs.
   */
  data: Prisma.XOR<Prisma.ChefUpdateManyMutationInput, Prisma.ChefUncheckedUpdateManyInput>
  /**
   * Filter which Chefs to update
   */
  where?: Prisma.ChefWhereInput
  /**
   * Limit how many Chefs to update.
   */
  limit?: number
}

/**
 * Chef updateManyAndReturn
 */
export type ChefUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * The data used to update Chefs.
   */
  data: Prisma.XOR<Prisma.ChefUpdateManyMutationInput, Prisma.ChefUncheckedUpdateManyInput>
  /**
   * Filter which Chefs to update
   */
  where?: Prisma.ChefWhereInput
  /**
   * Limit how many Chefs to update.
   */
  limit?: number
}

/**
 * Chef upsert
 */
export type ChefUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * The filter to search for the Chef to update in case it exists.
   */
  where: Prisma.ChefWhereUniqueInput
  /**
   * In case the Chef found by the `where` argument doesn't exist, create a new Chef with this data.
   */
  create: Prisma.XOR<Prisma.ChefCreateInput, Prisma.ChefUncheckedCreateInput>
  /**
   * In case the Chef was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ChefUpdateInput, Prisma.ChefUncheckedUpdateInput>
}

/**
 * Chef delete
 */
export type ChefDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
  /**
   * Filter which Chef to delete.
   */
  where: Prisma.ChefWhereUniqueInput
}

/**
 * Chef deleteMany
 */
export type ChefDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Chefs to delete
   */
  where?: Prisma.ChefWhereInput
  /**
   * Limit how many Chefs to delete.
   */
  limit?: number
}

/**
 * Chef without action
 */
export type ChefDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Chef
   */
  select?: Prisma.ChefSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Chef
   */
  omit?: Prisma.ChefOmit<ExtArgs> | null
}
